### ISSUE TITLE
Add Servo as a dependency and ensure that system can build with minimal external dependencies.

### ISSUE THREAD

**Issue by dkushner** [dkushner/jasper#3]
Ensure that the library can build at all with the hacky dependency on Servo "as-a-library." Currently the solution is to take Servo as a dependency in its entirety using the line:

```toml
[dependencies]
libservo = { git = "https://github.com/servo/servo.git" }
```

This brings all of Servo's core exports into scope for the project but also carries with it a lot of overhead. Modularizing the codebase is something that the Servo team is working towards.
